### ISSUE TITLE
[Part] Econometrics

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-econometrics-machine-learning#10]
Setup a `page` for econometrics in `python`

```
- caption: Econometrics
  numbered: true
  chapters:
  - file: statsmodels
```
