### ISSUE TITLE
[Part] Setup Section on Python Programming Tools

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-econometrics-machine-learning#11]
Needs to work out how this part relates to `python-programming.quantecon.org`

```
- caption: Programming Skills and Tools
  numbered: true
  chapters:
  - file: pandas
  - file: pandas_panel
```
