### ISSUE TITLE
[Part] Setup Machine Learning Topics

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-econometrics-machine-learning#9]
Setup a section for Machine Learning Topics

```yaml
- caption: Machine Learning
  numbered: true
  chapters:
  - file: scikit-learn
```
